"""
This module implements two state management classes for the DLQ Smart Router agent:
1. IdempotencyStore: A disk-backed, thread-safe key-value store using Python's native dbm. It tracks the occurrence count of message hashes to prevent duplicate processing, with TTL-based expiration and cleanup of expired keys. It is designed to survive container restarts and degrade gracefully if the underlying dbm file becomes unavailable or corrupted.
2. ClassificationCache: A memory-backed, thread-safe LRU cache with strict TTL enforcement. It is used for high-speed deterministic pattern matching and classification of messages. The cache size and TTL are configurable, and it supports basic operations like get, save, exists, and flush. The cache is designed for high-throughput scenarios where rapid access to classification results is critical, while maintaining thread safety and efficient memory usage.
"""

import dbm
import json
import logging
import os
import threading
import time
from typing import Optional

from cachetools import TTLCache


class IdempotencyStore:
    """
    Disk-backed, thread-safe key-value store using Python's native dbm.
    Survives container restarts to prevent mass duplicate processing.
    Attributes:
        db_path (str): The file path for the dbm database.
        lock (threading.Lock): A lock to ensure thread-safe access to the dbm file.
        logger (logging.Logger): Logger for logging errors and information.
    Methods:
        increment(hash_key: str, ttl_seconds: int = 86400) -> int:
            Increments the occurrence count for a given hash key and updates its TTL.
        cleanup_expired():
            Sweeps the dbm file to purge expired keys and prevent infinite disk growth.
    """

    # TODO: Idempotency is anchored on ClientID + MessageType + CorrelationID + PayloadHash. This is a heuristic approach and may not be universally applicable.
    # If correlation metadata is missing, duplicated payloads can be over-collapsed; if a legitimate retry changes payload or tracing metadata,
    # duplicates can slip through. This is an at-least-once safeguard, not exactly-once protection.
    # Consider allowing clients to provide a unique idempotency key in the message headers for more robust deduplication.
    # This could be dynamically generated by the client or derived from a combination of business identifiers, and would be validated against the idempotency store.
    # Challenge is that not all clients may have the ability to generate or provide such a key, and it may require additional coordination or schema changes on the client side.
    # Building in dynamic idempotency key mapping and validation to be a future enhancement, potentially with a pluggable strategy pattern
    # to allow different clients to provide their own idempotency keys or use a default hashing strategy.
    # Also see autonomous_dlq_classifier.py for the usage of IdempotencyStore in the DLQ processing pipeline, which demonstrates how the store is integrated with message classification and routing.

    def __init__(self, db_path=None):
        """Initialises the IdempotencyStore with a specified dbm file path.
        Args:
            db_path (str, optional): The file path for the dbm database. If not provided, it defaults to the environment variable 'IDEMPOTENCY_DB_PATH' or 'data/idempotency.db'.
        """

        # TODO: For scaling to high-throughput scenarios, particularly horizontal scaling, consider migrating from dbm to a more robust key-value store like Redis or Cosmos DB.

        # Parameterise DB path with .env fallback
        self.db_path = db_path or os.getenv(
            "IDEMPOTENCY_DB_PATH", "data/idempotency.db"
        )
        self.lock = threading.Lock()
        self.logger = logging.getLogger("IdempotencyStore")

        # CRITICAL PATCH: Ensure parent directory exists before dbm tries to create the file
        db_dir = os.path.dirname(self.db_path)
        if db_dir:  # Only attempt to create if a directory path actually exists
            os.makedirs(db_dir, exist_ok=True)

    def increment(self, hash_key: str, ttl_seconds: int = 86400) -> int:
        """Increments the occurrence count for a hash and updates its TTL.
        Args:
            hash_key (str): The unique hash key representing a message or operation.
            ttl_seconds (int): The time-to-live in seconds for the key before it expires.
        Returns:
            int: The updated occurrence count for the hash key.
        """
        with self.lock:
            try:
                with dbm.open(self.db_path, "c") as db:
                    now = int(time.time())
                    count = 0

                    key_bytes = hash_key.encode("utf-8")
                    if key_bytes in db:
                        try:
                            data = json.loads(db[key_bytes].decode("utf-8"))
                            if data.get("expires_at", 0) > now:
                                count = data.get("count", 0)
                        except (json.JSONDecodeError, ValueError):
                            # Corrupted or legacy format, gracefully reset
                            pass

                    count += 1
                    db[key_bytes] = json.dumps(
                        {"count": count, "expires_at": now + ttl_seconds}
                    ).encode("utf-8")

                    return count
            except Exception as e:
                # CRITICAL PATCH: Fail-Open Protocol.
                # If OS-level file permissions fail or DB corrupts, degrade gracefully.
                # Do not halt the main triage pipeline over a side-cache failure.
                self.logger.error(
                    f"Idempotency DB unavailable: {str(e)}. Failing OPEN."
                )
                return 1

    def cleanup_expired(self):
        """Sweeps the dbm file to purge expired keys and prevent infinite disk leak.
        This method should be called periodically to maintain the health of the idempotency store.
        It iterates through all keys in the dbm file, checks their expiration timestamps, and deletes any keys that have expired or are corrupted.
        """
        # TODO: [Tech Debt] Global lock contention.
        # This holds the thread lock during the full dictionary iteration.
        # Acceptable for MVP, but migrate to a concurrent DB (e.g., Redis/Cosmos) for high-scale prod.
        with self.lock:
            try:
                with dbm.open(self.db_path, "c") as db:
                    now = int(time.time())
                    keys_to_delete = []

                    for key in db.keys():
                        try:
                            data = json.loads(db[key].decode("utf-8"))
                            if data.get("expires_at", 0) <= now:
                                keys_to_delete.append(key)
                        except Exception:
                            keys_to_delete.append(key)  # Delete corrupted keys

                    for key in keys_to_delete:
                        del db[key]

                    if keys_to_delete:
                        self.logger.info(
                            f"Purged {len(keys_to_delete)} expired keys from Idempotency Store."
                        )
            except Exception as e:
                self.logger.error(f"Failed to execute idempotency cleanup: {e}")


class ClassificationCache:
    """
    Memory-backed, thread-safe LRU cache with strict TTL enforcement.
    Used for high-speed deterministic pattern matching.
    Attributes:
        cache (TTLCache): The underlying TTL cache from cachetools.
        lock (threading.Lock): A lock to ensure thread-safe access to the cache.
    Methods:
        get(key: str):
            Retrieves the value associated with the key from the cache, or None if not present.
        save(key: str, value: dict, ttl_seconds: Optional[int] = None):
            Saves a value in the cache with an optional TTL. If TTL is not provided, the default TTL from the cache initialisation is used.
        exists(key: str) -> bool:
            Checks if a key exists in the cache.
        flush():
            Clears all entries from the cache.
    """

    def __init__(
        self, maxsize: Optional[int] = None, ttl_seconds: Optional[int] = None
    ):
        """Initialises the ClassificationCache with optional max size and TTL.
        Args:
            maxsize (int, optional): The maximum number of items the cache can hold. Defaults to 10000 if not provided.
            ttl_seconds (int, optional): The time-to-live in seconds for each cache entry. Defaults to 600 seconds if not provided.
        """
        # CRITICAL PATCH: Strictly enforce environment variable precedence
        env_maxsize = int(os.getenv("CLASSIFICATION_CACHE_MAXSIZE", 10000))
        env_ttl = int(os.getenv("CLASSIFICATION_TTL_SECONDS", 600))
        active_maxsize = maxsize if maxsize is not None else env_maxsize
        active_ttl = ttl_seconds if ttl_seconds is not None else env_ttl

        self.cache: TTLCache[str, dict] = TTLCache(
            maxsize=active_maxsize, ttl=active_ttl
        )
        self.lock = threading.Lock()

    def get(self, key: str):
        """Retrieves the value associated with the key from the cache.
        Args:
            key (str): The key to look up in the cache.
        Returns:
            The value associated with the key if it exists and has not expired; otherwise, None.
        """
        with self.lock:
            return self.cache.get(key)

    def save(self, key: str, value: dict, ttl_seconds: Optional[int] = None):
        """Save a value using the cache-wide TTL.
        Args:
            key (str): The key under which to store the value.
            value (dict): The value to store in the cache.
            ttl_seconds (int, optional): Retained for caller compatibility. TTLCache applies the configured TTL to every entry, so this value is ignored.
        """
        with self.lock:
            self.cache[key] = value

    def exists(self, key: str) -> bool:
        """Checks if a key exists in the cache.
        Args:
            key (str): The key to check for existence in the cache.
        Returns:
            bool: True if the key exists in the cache and has not expired; otherwise, False.
        """
        with self.lock:
            return key in self.cache

    def flush(self):
        """Clears all entries from the cache."""
        with self.lock:
            self.cache.clear()
